# Generated by Django 4.2.1 on 2023-05-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionParameterToPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(blank=True, null=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi_app.function')),
            ],
        ),
    ]
