# Generated by Django 4.2.1 on 2023-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0002_functionparametertopass'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionparametertopass',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
