# Generated by Django 4.2.1 on 2023-05-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0003_functionparametertopass_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionparametertopass',
            name='function_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_input', to='pdi_app.function'),
        ),
    ]
