# Generated by Django 4.2.1 on 2023-05-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0004_functionparametertopass_function_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.JSONField(blank=True, null=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi_app.function')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi_app.task')),
            ],
        ),
        migrations.AlterField(
            model_name='functionparametertopass',
            name='function_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_input', to='pdi_app.taskoutput'),
        ),
    ]
