# Generated by Django 4.2.1 on 2023-05-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0007_rename_key_functionparametertopass_output_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionparametertopass',
            name='input_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
