# Generated by Django 4.2.1 on 2023-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0009_task_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionparametertopass',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('external', 'external')], default='internal', max_length=10),
        ),
    ]
