# Generated by Django 4.2.1 on 2023-05-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0010_functionparametertopass_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionparametertopass',
            old_name='type',
            new_name='input_type',
        ),
    ]
