# Generated by Django 4.2.1 on 2023-05-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0011_rename_type_functionparametertopass_input_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='alias',
        ),
    ]
