# Generated by Django 4.2.1 on 2023-05-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0012_remove_task_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alias',
            field=models.TextField(default='Alias', unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='funtion_input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pdi_app.task'),
        ),
    ]
