# Generated by Django 4.2.1 on 2023-06-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0014_alter_function_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoutput',
            name='output_type',
            field=models.CharField(blank=True, choices=[('dataframe', 'dataframe'), ('files', 'files')], max_length=10, null=True),
        ),
    ]
