# Generated by Django 4.2.1 on 2023-06-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0016_alter_taskoutput_output_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskoutput',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdi_app.case'),
        ),
    ]
