# Generated by Django 4.2.1 on 2023-06-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0017_taskoutput_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='funtion_input',
            new_name='input_function',
        ),
        migrations.AddField(
            model_name='task',
            name='custom_input_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_custom_input',
            field=models.BooleanField(default=False),
        ),
    ]
