# Generated by Django 4.2.1 on 2023-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0018_rename_funtion_input_task_input_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionparametertopass',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='functionparametertopass',
            name='multiple_input',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
