# Generated by Django 4.2.1 on 2023-06-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0019_functionparametertopass_is_multiple_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_input_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
