# Generated by Django 4.2.1 on 2023-06-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0020_alter_task_custom_input_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionparametertopass',
            old_name='config',
            new_name='dict_config',
        ),
        migrations.AddField(
            model_name='functionparametertopass',
            name='list_config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
