# Generated by Django 4.2.1 on 2023-06-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0025_alter_taskoutput_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskoutput',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
