# Generated by Django 4.2.1 on 2023-06-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0028_functionparametertopass_single_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='input_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdi_app.task'),
        ),
    ]
