# Generated by Django 4.2.1 on 2023-06-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0029_alter_task_input_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='external_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
