# Generated by Django 4.2.1 on 2023-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdi_app', '0030_function_external_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
